### PR TITLE
Add .vscode directory to .gitignore

### PR DESCRIPTION
**Pull request by julbean**

### CODE REVIEW

**Comment by julbean** [comment]
@linuxdaemon 
PR to remove a file specific to an environment (VS Code config) from repo

**Comment by linuxdaemon** [comment]
This was explicitly added as settings for this project as we need to disable whitespace trim for anyone using vscode, otherwise it will wipe out the indentation on blank lines

**Comment by julbean** [comment]
I understand you having the folder/config on your system, since you're using VS Code, but that seems like exactly the kind of thing .gitignore is for.  I don't think it's worth bloating the repo with config files for every editor that deletes blank line whitespace by default just so potential future contributors might save a minute if they happen to use that editor

**Comment by julbean** [comment]
I found a poll that says a substantial portion of Python devs use VS Code nowadays, so I actually think keeping it might be reasonable after all:
https://lp.jetbrains.com/python-developers-survey-2022/#DevelopmentTools
Did you say PyCharm also deletes blank line whitespace?  Could be worth adding a config for that one as well, given it has similar market share to VS Code (~30%).

**Comment by linuxdaemon** [comment]
Pycharm does yep, I can open the repo in my copy and see what the setting is

**Pull request closed without merging**
